version: 2

defaults: &defaults
  docker:
  - image: circleci/node:10.14.1
  working_directory: ~/project

jobs:
  lint_and_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-
      - run:
          name: dependencies_install
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: |
            echo "npm run linter"
      - run:
          name:
          command: |
            source ./.circleci/scripts/lint-result
      - run:
          name: Test package
          command: |
            npm test
      - run:
          name:
          command: |
            source ./.circleci/scripts/test-result
      - persist_to_workspace:
          root: ~/project
          paths:
          - .circleci

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Publish package
          command: |
            echo "npm run publish || true"

workflows:
  version: 2
  check_package:
    jobs:
      - lint_and_test
      - publish:
          requires:
            - lint_and_test
      - publish:
          requires:
            - lint_and_test
          filters:
            branches:
              only: develop
