version: 2

defaults: &defaults
  docker:
  - image: circleci/node:10.14.1
  working_directory: ~/project

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-
      - run:
          name: dependencies_install
          command: |
            npm install
      - save_cache:
          paths:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Test package
          command: |
            npm test
      - run:
          name:
          command: |
            source ./.circleci/scripts/test-result
      - persist_to_workspace:
          root: ~/project
          paths:
          - .circleci

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
        name: Publish package
        command: |
          echo "npm run semantic-release || true"

workflows:
  version: 2
  check_package:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: develop
