extends: airbnb
env:
  browser: true
  jest: true
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .js
      - .jsx
  no-nested-ternary: off
  import/no-extraneous-dependencies: off
  jsx-a11y/label-has-for: off
  react/forbid-prop-types: off
  react/jsx-one-expression-per-line: off
  react/jsx-no-bind: off
