server:
  port : 8080
  connection-timeout: 20000
  servlet:
    display-name: FlagBot
    context-path: /flagbot
  ssl:
    enabled: true
    key-store: ${certs}/server.keystore
    key-store-password: HQKQvJszAgKtgtRjtsR23KdYstMff6

email: symphonybot@daitangroup.com

session_auth:
  host: develop-api.symphony.com
  port: 8444

pod:
  host: develop.symphony.com

app-authentication:
  enabled: true
  api:
    enabled: true
    base-path: "/v1/application"
    keystore-file: ${certs}/daitan-bot-app.p12
    keystore-password: changeit
  filter:
    enabled: true
    url-patterns:
      - "/v1/*"
    excluded-paths:
      - "/v1/application/authenticate"
      - "/v1/application/tokens/validate"
      - "/v1/application/jwt/validate"
  pod:
    host: ${pod.host}
    port: ${pod.port:443}
  session_auth:
    host: ${session_auth.host}
    port: ${session_auth.port:443}

resources: '${user.dir}/src/main/resources'
certs: '${resources}/certs/'
bot-config: '${resources}/bot-config.json'
