export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

export const POST_NOTIFICATIONS = 'POST_NOTIFICATIONS';
export const POST_NOTIFICATIONS_SUCCESS = 'POST_NOTIFICATIONS_SUCCESS';
export const POST_NOTIFICATIONS_FAILURE = 'POST_NOTIFICATIONS_FAILURE';

export const DELETE_NOTIFICATIONS = 'DELETE_NOTIFICATIONS';
export const DELETE_NOTIFICATIONS_SUCCESS = 'DELETE_NOTIFICATIONS_SUCCESS';
export const DELETE_NOTIFICATIONS_FAILURE = 'DELETE_NOTIFICATIONS_FAILURE';
